## 服务注册与发现中心
eureka:
  instance:
    #eureka是使用hostname进行注册的，使用IP进行注册
    prefer-ip-address: true
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 60
    # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 15
    # 将Instance ID设置成IP
    instance-id: ${spring.cloud.client.ipAddress}
    metadata-map:
      # 服务集群
      cluster: TEST
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8761/eureka/,http://eureka3:8761/eureka/
ribbon:
  eureka:
    # 默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，而是使用静态配置的服务列表。
    enabled: true

spring:
  application:
    name: spring-cloud-hystrix-turbine
server:
  port: 8031
security:
  basic:
    enabled: false
turbine:
  aggregator:
    # 指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
    clusterConfig: default
  ## 配置Eureka中的serviceId列表，表明监控哪些服务
  appConfig: spring-cloud-consumer,spring-cloud-provider
  clusterNameExpression: new String("default")
  # 1. clusterNameExpression指定集群名称，默认表达式appName；此时：turbine.aggregator.clusterConfig需要配置想要监控的应用名称
  # 2. 当clusterNameExpression: default时，turbine.aggregator.clusterConfig可以不写，因为默认就是default
  # 3. 当clusterNameExpression: metadata['cluster']时，假设想要监控的应用配置了eureka.instance.metadata-map.cluster: ABC，则需要配置，同时turbine.aggregator.clusterConfig: ABC